services:
  foxglove:
    image: icon/foxglove
    # build:
    #   context: ..
    #   dockerfile: ./Dockerfile
    ports:
      - 80:8080
    volumes:
      - ./foxglove_layout.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - UI_PORT=8080
      - DISABLE_CACHE=true
      - DISABLE_INTERACTION=false
