[program:robot_disco_foxglove_bridge]
command=/usr/bin/env bash -lc "source /home/rd/rd_ws/install/setup.bash && ROS_DOMAIN_ID=0 ros2 launch robot_disco foxglove_bridge_launch.xml"
directory=/home/rd/rd_ws
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/rd/rd_ws/log/robot_disco-foxglove.out.log
stderr_logfile=/home/rd/rd_ws/log/robot_disco-foxglove.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=2
stderr_logfile_backups=2
environment=HOME="/home/rd"
user=rd
