[program:robot_disco_collision_monitor]
command=/usr/bin/env bash -lc "source /home/rd/rd_ws/install/setup.bash && ROS_DOMAIN_ID=0 ros2 launch nav2_collision_monitor collision_monitor_node.launch.py param_file:='/home/rd/rd_ws/src/robot_disco/config/collision_monitor_params.yaml '"
directory=/home/rd/rd_ws
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/rd/rd_ws/log/robot_disco-localization.out.log
stderr_logfile=/home/rd/rd_ws/log/robot_disco-localization.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=2
stderr_logfile_backups=2
environment=HOME="/home/rd"
user=rd