[program:robot_disco_foxglove_studio]
command=/usr/bin/docker run --rm --name foxglove --publish 8080:8080 --volume /home/rd/rd_wd/foxglove_studio/foxglove-layout.json:/foxglove/default-layout.json RobotDisco/foxglove
directory=/home/rd/rd_ws/foxglove_studio
autostart=true
autorestart=true
startsecs=10
stopsignal=INT
stopwaitsecs=10
stdout_logfile=/var/log/foxglove.out.log
stderr_logfile=/var/log/foxglove.err.log
user=rd
environment=HOME="/opt/foxglove"
