[program:robot_disco_ur5e_driver]
command=/usr/bin/env bash -lc "source /home/rd/rd_ws/install/setup.bash && ROS_DOMAIN_ID=0 ros2 launch robot_disco ur5e.launch.py"
directory=/home/rd/rd_ws
autostart=false
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/home/rd/rd_ws/log/robot_disco-ur5e-driver.out.log
stderr_logfile=/home/rd/rd_ws/log/robot_disco-ur5e-driver.err.log
stdout_logfile_maxbytes=20MB
stderr_logfile_maxbytes=20MB
stdout_logfile_backups=2
stderr_logfile_backups=2
environment=HOME="/home/rd"
user=rd
